'use strict'
module.exports = {
    MAIN: '/',
    REGISTRATION: '/reg',
    EP: '/ep',
    SUBJ: '/subj',
    ENTRANCE: '/entr',
    LOGOUT: '/logout',
    SETTINGS: '/settings',
    PROFILE: '/profile',
    FILTERED_SUBJECTS: '/filter',
    CREATE_REVIEW: '/createReview',
    DATA: '/data',
    REVIEWS: '/reviews',
    PASSWORD: '/password',
    RATE: '/rate',
    REPLY: '/reply',
    TEACHERS: '/teachers',
    ADMIN: '/admin',
    NEW: '/new',
    SUBJECT: '/subject',
    EDIT: '/edit',
    TEACHER: '/TEACHER',

    // revSubj: '/revSubj',
};